version: '3.3'

services:  
  node-crud: 
    container_name: vehicles_registration
    build: ./node-crud
    depends_on:
      -   postgres
    ports:
      - "${PORT}:${PORT}"

  postgres:
    container_name: postgres_container
    image: postgres:14.1        
    environment:      
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_TEST_NAME: ${DB_TEST_NAME}
      PGDATA: /data/postgres    
    volumes:
       - ./postgres:/data/postgres     
       - ./node-crud/src/database/scripts:/docker-entrypoint-initdb.d/
     
     
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - node-vehicles
    restart: unless-stopped
  
  
 
networks:
  node-vehicles:
    driver: bridge

volumes:
    mssql: